### ISSUE TITLE
unable to start examples of igvShinyDemo-customGenome-localFiles.R

### ISSUE THREAD

**Issue by tboonf** [gladkia/igvShiny#79]
Hi - I have been trying to load my own files using igvShiny but it hasnt been working. So I tried a few examples igvShinyDemo-customGenome-http.R, igvShinyDemo-customGenome-localFiles.R and none of them work. Its works  when files are sourced from https but not for files uploaded locally. 

_____For example the script that comes with igvShiny doesnt work even though the fasta, fai and gff3 actually exist in the right directory----
library(shiny)
library(igvShiny)
library(htmlwidgets)
# library(biomaRt)

#----------------------------------------------------------------------------------------------------
data.directory <- system.file(package="igvShiny", "extdata")
fasta.file      <- file.path(data.directory, "ribosomal-RNA-gene.fasta")
fastaIndex.file <- file.path(data.directory, "ribosomal-RNA-gene.fasta.fai")
annotation.file <- file.path(data.directory, "ribosomal-RNA-gene.gff3")

genomeOptions <- parseAndValidateGenomeSpec(genomeName="ribo local",
                                            initialLocus="U13369.1:7,276-8,225",
                                            stockGenome=FALSE,
                                            dataMode="localFiles",
                                            fasta=fasta.file,
                                            fastaIndex=fastaIndex.file,
                                            genomeAnnotation=annotation.file)

#----------------------------------------------------------------------------------------------------
ui = shinyUI(fluidPage(
    igvShinyOutput('igvShiny_0'),
    ))
#----------------------------------------------------------------------------------------------------
server = function(input, output, session) {

   output$igvShiny_0 <- renderIgvShiny({
     cat("--- starting renderIgvShiny\n");
     x <- igvShiny(genomeOptions,
                   displayMode="SQUISHED",
                   )
     cat("--- ending renderIgvShiny\n");
     return(x)
     })

} # server
#----------------------------------------------------------------------------------------------------
if(grepl("hagfish", Sys.info()[["nodename"]]) & !interactive()){
   runApp(shinyApp(ui, server), port=6867)
   } else {
   shinyApp(ui, server)
   }

**Comment by ChristianRohde** [comment]
Hi, I support your observation! May I ask which version of igvShiny you are using? I guess I have a similar problem with the latest version 1.0.0 installed from Bioconductor working on R version 4.4.0 (2024-04-24) while things work nice on another server with igvShiny version **0.99.0** on R version 4.3.1 (2023-06-16). I think I remember that I also commented here on another issue a while ago, that I needed to go back to an older version of igvShiny because of similar trouble. For now I went back to version 0.99.0 and this works for me. In addition I observed the same problem on R version 4.4.1 (2024-06-14) on my Macbook. Also here I switched back and force with the same effect. This is how to install the old version:

1. install.packages("remotes")
2. library(remotes)
4.  remotes::install_github("https://github.com/gladkia/igvShiny", ref="4327f67a710e0f61b27f59d3453a655740245212", upgrade = FALSE, type="source", force = TRUE)
5. q() to restart the R session

For me the old igvShiny version 0.99.0 allows me to load custom genomes from system.file(package="igvShiny", "extdata") as you show above. I attached my current test script of the igvShiny custom genome from localFiles stuff in which I use the genome from the extdata source:

[igvshiny_custom_genome_2024.zip](https://github.com/user-attachments/files/16561176/igvshiny_custom_genome_2024.zip)

In addition on my productive servers I load these custom genomes from folder from my local environment. I define the files this way: 

igvShiny_genome_rRNA <- base::normalizePath("path/2/igvShiny_genome_folder")
data.directory <- base::normalizePath(igvShiny_genome_rRNA)
fasta.file <- base::paste0(data.directory,"/sequence.fasta")
fastaIndex.file <- base::paste0(data.directory,"/sequence.fasta.fai")
annotation.file <- base::paste0(data.directory,"/sequence.gff3")

I hope this helps.

Btw @gladkia the new version also has another bug without any meaningful error on command line. Just a very cryptic message in the GUI: 
![Screenshot 2024-08-09 at 14 35 40](https://github.com/user-attachments/assets/72386789-5dd0-4a78-a2f7-fb6751a23ac1)

Here I am not able to load reads from local bam files any more. Actually I do see the reads being loaded and processed based on the prints from my code. But I do not get this information into igvShiny with the current version. The old version also does not have this bug but shows the expected track (I zoomed in a bit more to make sure we see something in the screenshot):

![Screenshot 2024-08-09 at 14 45 21](https://github.com/user-attachments/assets/b5be9c08-2b01-41f9-b9f1-c780611a6f43)

Best,
Christian

**Comment by ChristianRohde** [comment]
@paul-shannon maybe you have an idea what happened. It seems that nobody noticed this issue. Please have a look above

**Comment by ChristianRohde** [comment]
Yes sure, I just mentioned you @paul-shannon since your version is the one which works for me. I am not sure about other later versions, since I did not test. In addition I wanted to make sure that we generate some traffic here, since I realized that there was no comment on this issue since a month. Thank you again for this wonderful package and I love that we can install it from Bioconductor now!

**Comment by gladkia** [comment]
Hi @paul-shannon, thanks for the good words of support and continuous inspiration! I hope you enjoy the new chapter of your life!

**Comment by gladkia** [comment]
@tboonf, @ChristianRohde the issue has been fixed with small changes in https://github.com/gladkia/igvShiny/pull/81.

**Comment by gladkia** [comment]
@ChristianRohde can you check if the second issue you spotted is still present? Can you create a new issue if so? Thanks.
